# path to JSON file with population codes
POP_CODES: populations.json

# paths to relevant data files
chromosomes:
  chrX: data/ALL.chrX.phase3_shapeit2_mvncall_integrated_v1b.20130502.genotypes.vcf.gz
  chrY: data/ALL.chrY.phase3_integrated_v2a.20130502.genotypes.vcf.gz
  chr8: data/ALL.chr8.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
  chr9: data/ALL.chr9.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz

panel:
  - data/integrated_call_samples_v3.20130502.ALL.panel

callable_sites:
  - data/20141020.strict_mask.whole_genome.bed

#chromosome filters
filters:
  filter1:
    - UCSC_refseq_gencode_gene_transcripts_hg19.bed
    - simple_repeats_hg19.bed
    - centromere_telomere_hg19.bed
    - CpG_islands_hg19.bed
  filter2:
    - UCSC_refseq_gencode_gene_transcripts_1kb_buffer_hg19.bed
    - simple_repeats_hg19.bed
    - centromere_telomere_hg19.bed
    - CpG_islands_hg19.bed
  filter3:
    - UCSC_refseq_gencode_gene_transcripts_5kb_buffer_hg19.bed
    - simple_repeats_hg19.bed
    - centromere_telomere_hg19.bed
    - CpG_islands_hg19.bed
  filter4:
    - UCSC_refseq_gencode_gene_transcripts_10kb_buffer_hg19.bed
    - simple_repeats_hg19.bed
    - centromere_telomere_hg19.bed
    - CpG_islands_hg19.bed
  filter5:
    - UCSC_refseq_gencode_gene_transcripts_20kb_buffer_hg19.bed
    - simple_repeats_hg19.bed
    - centromere_telomere_hg19.bed
    - CpG_islands_hg19.bed
  filter6:
    - UCSC_refseq_gencode_gene_transcripts_50kb_buffer_hg19.bed
    - simple_repeats_hg19.bed
    - centromere_telomere_hg19.bed
    - CpG_islands_hg19.bed
  filter7:
    - UCSC_refseq_gencode_gene_transcripts_100kb_buffer_hg19.bed
    - simple_repeats_hg19.bed
    - centromere_telomere_hg19.bed
    - CpG_islands_hg19.bed
  filter_all:
    - UCSC_refseq_gencode_gene_transcripts_hg19.bed
    - simple_repeats_hg19.bed
    - centromere_telomere_hg19.bed
    - CpG_islands_hg19.bed
    - segmental_duplications_hg19.bed

# windows for Analysis
windows:
  100kb:
    win_size: 100000
    overlap: False
    slide_size: 0
  100kb-50kb-overlapping:
    win_size: 100000
    overlap: True
    slide_size: 50000
  byRegion:
    win_size: null
    overlap: False
    slide_size: null

# ld bin size
ld_bins:
  300kb:
    size: 300

# parameters for the max height of the diversity plots
# chr9 heights need to be edited
uncorrected:
  chrX: 0.004
  chrY: 0.0003
  chr8: 0.004
  chr9: 0.006
rheMac2-hg19-corrected:
  chrX: 0.045
  chrY: 0.04
  chr8: 0.055
  chr9: 0.05
canFam3-hg19-corrected:
  chrX: 0.02
  chrY: 0.02
  chr8: 0.02
  chr9: 0.025
calJac3-hg19-corrected:
  chrX: 0.03
  chrY: 0.03
  chr8: 0.03
  chr9: 0.05
