# path to JSON file with population codes
POPS_CODES: "populations.json"

# paths to relevant data files
CHR_X_VCF: "data/ALL.chrX.phase3_shapeit2_mvncall_integrated_v1b.20130502.genotypes.vcf.gz"
CHR_Y_VCF: "data/ALL.chrY.phase3_integrated_v2a.20130502.genotypes.vcf.gz"
CHR_8_VCF: "data/ALL.chr8.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz"
